- examples/script/assert.http
- examples/script/chai.http
None
The `JSON.parse(response.body)` is unnecessary since [httpResponse](https://github.com/AnWeber/httpyac/blob/main/src/models/httpResponse.ts) already contains the body as JSON.
This is my first contribution, so I am not sure I have done it right.
> Removed unnecessary JSON parses

- src/utils/requestUtils.ts
When decoding access tokens we should use the built-in encoding `base64url` instead of trying to do our own base64-URL-safe decoding.
The existing code throws `URIError: URI malformed` for perfectly valid access tokens issued by Microsoft IDP. The proposed change now decodes these access tokens without error.
> Use built-in base64 URL-safe buffer encoding

- src/variables/replacer/oauth/refreshTokenFlow.ts
When a OAuth2 token redemption request succeeds and provides a `refresh_token`, but does not provide an expiration for the refresh token, subsequent uses of the oauth2 session (after the initial `access_token` has expired) will trigger a full re-authentication as the `RefreshTokenFlow.perform` method requires the `refreshExpiresIn` to be defined on the OpenID information object.
This proposal relaxes this requirement to be more inline with the OAuth2 specification and the type definition of the `OpenIdInformation` interface who both state this property to be optional.
In this proposal, if a `refresh_token` is available, but no expiration is defined, the `RefreshTokenFlow.perform` will attempt to refresh.
> Make refresh token expiration optional

- src/parser/parserUtils.ts
Blank header field caused header parsing failure. As a result, the subsequent header section would be mistaken as request body. Minimal example:
```
###
POST https://httpbin.org/anything
user-abi: 
user-token: 1234567
```
> fix: blank header value caused request failure

- src/cli/cliOptions.ts
- src/variables/replacer/oauth/authorizationCodeFlow.ts
- src/variables/replacer/oauth/implicitFlow.ts
- src/variables/replacer/oauth/openIdConfiguration.ts
- src/variables/replacer/oauth/openIdHttpserver.ts
- test/variables/replacer/oauth/openIdConfiguration.test.ts
- solves #118 
- validates `redirectUri`
Uses existing `var` functionality
```bash
httpyac file.http --all --var oauth2_redirectUri=http://localhost:1234/some/path
```
or
```bash
httpyac file.http --all --var myPrefix_redirectUri=http://localhost:9000
```
or
```bash
oauth2_redirectUri=http://0.0.0.0:7000/callback
```
or
```bash
@oauth2_redirectUri=http://whatever.com/
```
> Configure callback

- src/actions/httpClientAction.ts
When using `noRejectUnauthorized` in meta, Got threw warning:
```
(node:24393) DeprecationWarning: Got: "options.rejectUnauthorized" is now deprecated, please use "options.https.rejectUnauthorized"
```
it's fixed with this :)
> Fix Got deprecation warning.

- src/models/httpHooksApi.ts
- src/store/httpFileStore.ts
~~Adds a new property `httpyac` to the `HttpyacHooksApi` type.~~
Adds a new property `utils` to the to the `HttpyacHooksApi` type.
This will enable a plugin or a `configureHooks` function provided by `.httpyac.js` to use the exported functions in the `httpyac` module from memory without the need of resolving/requiring the module.
This has the benefit that a no-dependencies plugin or a standalone `.httpyac.js` can run in the context of httpyac without any additional steps. It will also ensure that a plugin *sees* the same APIs as the runtime it is extending. Typically a plugin could now only add a `devDependency` on `httpyac` to get type definitions, but the original way of doing thing would still work seamlessly (you'd just ignore the new property).
> Add httpyac runtime reference to plugin api

- src/cli/send/jsonOutput.ts
- src/models/httpResponse.ts
- src/utils/gotUtils.ts
- src/utils/requestUtils.ts
- test/utils/gotUtils.test.ts
As per the documentation from node.js (which is also used by got), HTTP headers from the response are (in most cases) merged together by joining multiple values from equal-named headers with `', '`. (I.e. multiple x-some-header headers are combined to one header value with `<value1>, <value2>, etc.`).
In most cases that is fine as there is some special handling for some default headers (e.g. `User-Agent` (multiple values are discarded) and `Set-Cookie` (value is always an array).
However, I find myself in a situation where I need to handle multiple values for a header. And to makes matters even worse, I need to parse these headers and the syntax I am parsing contains `,`. In such a case the intelligent header handling of got is not helpful.
For such purposes I propose that we add a new …
> Add rawHeaders to HttpResponse

- src/parser/requestHttpRegionParser.ts
- src/variables/replacer/hostVariableReplacer.ts
support absolution path as uri, e.g.
```
GET /get HTTP/1.1
Host: httpbin.org
```
see [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html)
>  support absolute path as uri

- src/plugins/oauth2/flow/authorizationCodeFlow.ts
- src/plugins/oauth2/flow/clientCredentialsFlow.ts
- src/plugins/oauth2/flow/deviceCodeFlow.ts
- src/plugins/oauth2/flow/implicitFlow.ts
- src/plugins/oauth2/flow/passwordFlow.ts
When you have multiple active oauth2 sessions that use different services from the same token authority the cache key of the oauth2 session overlaps. This forces a re-authentication and is very annoying.
I propose that the variable prefix is included in the cache key so that oauth2 sessions are kept seperate.
Example:
I have scenarios where I authenticate to multiple M365/Azure AD services, notably SharePoint and Microsoft Graph. Both are authorized by the Microsoft Identity platform token service, meaning the clientId and the tokenEndpoint is the same, but I have different scopes and therefore different variable prefixes. There are also other scenarios where I'd want to test access to an API with two different users in which case I'd have two prefixes, but all other variables would be …
> Add oauth2 variable prefix to cache key

- src/plugins/oauth2/flow/authorizationCodeFlow.ts
- src/plugins/oauth2/flow/passwordFlow.ts
- src/plugins/oauth2/flow/requestOpenIdInformation.ts
According to OAuth2 specifications both the ROPC and authorization code grant flows can be used with public clients (clients without a secret). This PR relaxes the requirements that a clientSecret needs to be specified when using these flows.
Also when issueing a request to the token endpoint, the Authorization header with basic credentials (using client id and secret) should only be used when both client Id and client secret values are set (in addition to the `useAuthorizationHeader` config variable). As per OAuth specification, the Authorization header must not be used with a public client (i.e. when the client secret is not specified).
The Microsoft Identity platform allows for public clients in all of their OAuth2 flows and instead allow for configuration when the OAuth2 is registered …
> OAuth2 allow usage of public clients

- src/models/openIdInformation.ts
- src/plugins/oauth2/flow/authorizationCodeFlow.ts
- src/plugins/oauth2/flow/clientCredentialsFlow.ts
- src/plugins/oauth2/flow/deviceCodeFlow.ts
- src/plugins/oauth2/flow/implicitFlow.ts
- src/plugins/oauth2/flow/passwordFlow.ts
- src/plugins/oauth2/flow/refreshTokenFlow.ts
- src/plugins/oauth2/openIdConfiguration.ts
[RFC 8707 Resource Indicators for OAuth 2.0](https://www.rfc-editor.org/rfc/rfc8707.html) defines the `resource` parameter in an OAuth2 token request.
> [This RFC defines] request parameters that enable a client to explicitly signal to an authorization server about the identity of the protected resource(s) to which it is requesting access.
Some Token Authorization services require the use of the `resource` parameter *in addition to* or *instead of* the `scope` and `audience` parameters for multi-tenant or multi-service scenarios.
An example of this is the Azure Access Control Service which is used to obtain App-Only access tokens for SharePoint Online. The `resource` parameter controls for which SharePoint online instance the access is granted instead of issuing an access token for all …
> Add optional OAuth2 resource parameters

- .vscode/launch.json
The default console for VS Code is the internal console. The problem with the internal console is that it cannot be used with user interaction. This PR suggest to use an integrated terminal window instead, allowing to debug http files that use script code using the `userInteractionProvider`.
Httpyac is also not a node.js web application, but a console app. Changing the debugger type to reflect this.
> VS Code launch debugger in integrated terminal

- src/plugins/oauth2/oauth2VariableReplacer.ts
- src/plugins/oauth2/openIdConfiguration.ts
The previous code to read OAuth2 configuration from variables was capable of this from strings and non-falsy values only. A variable that was somehow (e.g. in JSON configuration) set to a value of `0` or `false` could not be set to a `true`-defaulting configuration property (e.g. `useAuthorizationHeader`).
The PR splits up the functionality to read variables to config by creating `getString()` and `getBooleanLike()`. The getter now only falls back additional sources (`oauth2_varname` -> `oauth2.varname` and `prefix_value` -> `oauth2_value`) when the value read is `undefined` or `null`, thus allowing for an actual value of `0` or `false`.
Additionally, if a OAuth2 session was created by script, the previous equality comparison would in some cases erroneously compare two OAuth2 …
> Oauth2 Configuration loading and equality comparison

- src/plugins/core/metaData/importMetaDataHandler.ts
- src/plugins/core/metaData/refMetaDataHandler.ts
- src/utils/httpRegionUtils.ts
This PR introduces dependency tracking for `@ref` and `@import` directives.
When an `@import` directive is processed:
* Add the current HttpRegion as a dependent to each of the imported file's global script regions.
When a `@ref` directive is processed:
* Add the current HttpRegion as a dependent to the referenced HttpRegion.
When `processHttpRegionActions` is called:
* Recursively go though all dependents that were previously added and reset them.  
Resetting means deleting the `response` property and all variables stored from previous execution (if any).
The dependents for each region is tracked in an array property named `refDependencies` on `ProcessorContext.options`. Each item in the array contains a `dependents` array that refers to the dependent regions that need to be reset, when …
> @import and @ref track dependencies

- src/__tests__/httpYacApi.test.ts
Yet another e2e cleanup. Again with to goal to increase readability and focus.
1. IMHO the check if the `send` was successful ( or Truthy) is redundant. 'cause if not, all later asserts would fail anyway. Same with array length of requests - unless its part of the actual assertions.
2. To clearly indicate the test structure of 1. setup 2. execution 3. assertion, each section is now separated with an empty line.
> E2e Test: add whitespace & remove redundancy

- src/cli/send/send.ts
Currently the CLI ends with printing the message `<number> requests tested (<number> succeeded, <number> failed).`.
I agree that httpyac often will be used when testing APIs, but the description on the [httpyac homepage](https://httpyac.github.io/) indicates that httpYac is a
general-purpose utility.
I propose that we change the word `tested` to `processed` to reflect the general-purpose nature of the tool. In cases when httpyac is used as a testing tool the 
new message `processed` is still correct.
> Change CLI result message for general purpose usages

- src/models/httpRegion.ts
- src/store/httpFileStore.ts
- src/utils/httpRegionUtils.ts
A non-global httpRegion should implicitly be dependent on the global regions of the file.
Since global regions are always executed when `@import`-ing or directly executing a region in a file, it is not helpful to invalidate their dependents when global regions are executed. Since a global region cannot be `@ref`-ed in itself that is okay.
Having the dependency tracking on the context is not ideal: the context is recreated every time the httpyac-CLI or VS Code execute a region or file. Instead dependency tracking should really be a feature of the region itself.
This makes the `context` argument for the `registerRegionDependent` and `resetDependentRegions` functions obsolete. I kept the argument (and retyped it to `any`) to keep backwards compatibility.
> Improve httpRegion dependency tracking

- src/__tests__/httpYacApi.test.ts
- src/plugins/http/digestAuthVariableReplacer.ts
Simple fix to use username that includes space.
This just follows an idea from `Basic Authentication HTTP` plugin - using ':' in such cases.
See https://httpyac.github.io/guide/variables.html#basic-authentication
Had problems to test it on [httpbin](https://httpbin.org) API, but on real system it worked for me.
If you like this idea highly probably docs need to be updated as well ;)
> feat: add user with space in http auth digest

- src/plugins/core/metaData/refMetaDataHandler.ts
When using the `ref` directive in an Http Region, we currently simply assign the `variablesPerEnv[envKey]` of the referenced region to the variables of the currently executing context.
It turns out that this is not sufficient for tracking transitive `ref`s (i.e. `ref` of a `ref`).
Therefore, I propose that we change the implementation in `refMetaDataHandler` to use the `utils` function `setVariableInContext` instead of a simple `Object.assign`. This will properly store both direct and transitive referenced variables in `variablesPerEnv[envKey]`.
> Set referenced HttpRegion variables properly in context

- src/cli/index.ts
- src/cli/initCliProvider.ts
I am using httpyac without CLI interface, and directly in JS code:
```js
async function run(content) {
initFileProvider(); // not accessible, I had to copy this from httpyac into my file
const httpFileStore = new store.HttpFileStore();
const httpFile = await httpFileStore.getOrCreate('file.http', async () => (content), 0, {});
const httpRegion = httpFile.httpRegions[0];
const context = {httpFile, httpRegion, processedHttpRegions: []};
const result = await send(context);
return context.processedHttpRegions[0];
}
run(`GET https://dev.our-website.com/path/1`)
```
Being able to conveniently initialize it with defaults is useful.
> Publish `initFileProvider` function

- src/plugins/graphql/gqlAction.ts
- src/plugins/graphql/gqlHttpRegionParser.ts
- src/store/httpRegion.ts
- src/test/request/graphql.spec.ts
This PR add the ability to use variable as GraphQL query variables, e.g.
```
{{
exports.variables = {
"limit": 10
};
}}
POST  http://localhost:7002/graphql
query launchesQuery($limit: Int!){
launchesPast(limit: $limit) {
mission_name
}
}
{{ variables }}
```
OR
```
{{
exports.variables = {
"foo": 10,
"bar": 20
};
}}
POST  http://localhost:7002/graphql
query launchesQuery($limit: ComplexInput!){
launchesPast(limit: $limit) {
mission_name
}
}
{
"limit": {{ variables }}
}
```
Above requests raise exception in current version, because `JSON.parse` was hooked on `execute` event, which happens before variable replacement.
> fix: unable to use variable as graphql input

- src/plugins/javascript/moduleUtils.ts
- src/test/variables/variables.spec.ts
pretty useful to be able to run asynchronous functions and collect data to pass to a request
> Allow async/await syntax in code snippets

- .npmignore
When installing httpyac as a depdendency, e.g. when develing httpyac-plugins the downloaded package from npmjs includes additional files that are unnecessary to be bundled in the package.
When using TypeScript aware editors (e.g. VSCode), the tsconfig.json files in the package are picked up when doing `Go to definition` actions. This leads to temporary false-positive error messages in VS Code (since the .ts files are not included in the package and the tsconfig thus does not find any matching files.)
I have added several rules for files that currently are included, but unnecessary. I use [JSDelivr](https://www.jsdelivr.com/package/npm/httpyac?tab=files) for viewing which files are included in the npm distributed package.
> Add additional npmignore rules

- .github/workflows/publish.yml
Extending the docker build task to build images for platforms: linux/amd64, linux/arm64 which enables native Apple Silicon support
FYI: that's just a c&p from https://github.com/marketplace/actions/build-and-push-docker-images I couldn't test it so far
> Add support for linux/arm64 docker images

- src/cli/send/jsonOutput.ts
- src/cli/send/options.ts
- src/cli/send/send.ts
- src/utils/requestUtils.ts
fix 2 problems
1. Multi-word options, e.g. `output-failed` and `repeat-mode` were not parsed correctly. See [documentation of commander](https://github.com/tj/commander.js#options )
2. `output-failed` option was ignored if `output` option was set to `none`
see https://github.com/AnWeber/httpyac/issues/460
> fix: `output-failed` didn't work

- src/models/httpHooksApi.ts
- src/store/httpFileStore.ts
Adds the `httpClientProvider` and `javascriptProvider` singletons from `io` to the `HttpyacHooksApi` interface.
If a plugin needs to do HTTP requests as part of its implementation it would be advantageous if the plugin could perform HTTP requests in the exact same way that Httpyac does. In doing so, the plugin would now no longer need to depend on an http-client, e.g. got, itself.
When executing a script block in an HttpRegion the executed code gets access to a set of default modules (e.g. `httpyac` itself, `dayjs`, `vscode`, etc.). However, plugin authors do not get access to these modules. Moreover, some of these modules are in itself extendable (e.g. dayjs), but a plgin would have no direct means to access these.
Currently a plugin would need to call `utils.replaceVariables` and supply …
> Add httpClientProvider and javascriptProvider to HttpHooksApi

- package.json
Removes indirect dependency on vulnerable vm2 package. 
https://github.com/advisories/GHSA-cchq-frgv-rjh5
> Update package.json: devs: mockttp ^3.8.0 -> ^3.9.1

- src/plugins/assert/assertHttpRegionParser.ts
- src/test/parser/parser.spec.ts
vscode plugin outline is broken when assert if used. e.g.
```
GET https://httpbin.org/anything
?? status == 200
```
After investigation, I found that issue might be related how regexp is written. I added test and default values in order to be null safe.
> Assert symbol not resolved fix

- src/cli/send/junitUtils.spec.ts
- src/cli/send/junitUtils.ts
the duration calculation for testCase assertions is totally a hack. Also the filename being relative to repo root allows gitlab to link to the file in the repo directly.
> fix: add classname, time and file to testcases

- src/plugins/core/registerCorePlugin.ts
https://github.com/AnWeber/vscode-httpyac/issues/258
> Fix for #258 Variable replacement doesn't work when file is injected in multipart/form-data request

- src/plugins/http/basicAuthVariableReplacer.ts
- src/plugins/http/test/basicAuth.spec.ts
If the password is not in the regex match, the function will not encode the header and instead return "Basic user:", which is what gets sent in the request.
Refs #751
> Add support for basic auth with no password using colon syntax.

- src/cli/send/plugin/testExitCodeInterceptor.ts
Fixes https://github.com/AnWeber/httpyac/issues/876.
Is this the right place to fix?
Should errored tests have a different non-zero exit code to failed tests?
> fix: return non-zero exit code for errored test
